module.exports = {
    MONGO_HOST: "cluster1.dvwspor.mongodb.net",
    MONGO_PASSWORD: "3X43SMrz7pNJ7zpu",
    MONGO_DBNAME: "RestaurantBusinessListing",
    MONGO_USERNAME: "e-commerce",

    TOKEN_SECRET_KEY: "PURPOSE IS TO KNOW THE ETERNAL TRUTH",
    ALGORITHM: "HS256",
    ALLOW_REFRESH: true,

    ROLES : ["BUSINESS OWNER", "ADMIN","USER"],
    CREATELISTINGROLE : ["BUSINESS OWNER", "ADMIN"],
    GETLISTINGROLE : ["BUSINESS OWNER", "ADMIN","USER"],
    UPDATELISTINGROLE : ["BUSINESS OWNER", "ADMIN"],
    DELETELISTINGROLE : ["ADMIN"],

    REVIEWROLE : ["USER", "ADMIN"],
    REVIEWRESPONSEROLE : ["BUSINESS OWNER", "ADMIN"],
};
